[package]
name = "golamd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
golam-core = { path = "../golam-core" }
golam-effects = { path = "../golam-effects" }
golam-ipc = { path = "../golam-ipc" }
golam-kernel = { path = "../golam-kernel" }
getrandom.workspace = true

[lints]
workspace = true
